const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
  SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

  //user
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  PROCESS_LOGOUT: 'PROCESS_LOGOUT',

  //admin
  FETCH_GENDER_START: 'FETCH_GENDER_START',
  FETCH_GENDER_START_SUCCESS: 'FETCH_GENDER_START_SUCCESS',
  FETCH_GENDER_START_FAILURE: 'FETCH_GENDER_START_FAILURE',

  //position
  FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
  FETCH_POSITION_FAILURE: 'FETCH_POSITION_FAILURE',

  //role
  FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
  FETCH_ROLE_FAILURE: 'FETCH_ROLE_FAILURE',

  //save
  SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
  SAVE_USER_FAILURE: 'SAVE_USER_FAILURE',

  //fetch all user
  FETCH_ALL_USERS_START: 'FETCH_ALL_USERS_START',
  FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
  FETCH_ALL_USERS_FAILURE: 'FETCH_ALL_USERS_FAILURE',

  //delete all user
  DELETE_A_USER_START: 'DELETE_A_USER_START',
  DELETE_A_USER_SUCCESS: 'DELETE_A_USER_SUCCESS',
  DELETE_A_USER_FAILURE: 'DELETE_A_USER_FAILURE',

  //edit a user
  EDIT_A_USER_SUCCESS: 'EDIT_A_USER_SUCCESS',
  EDIT_A_USER_FAILURE: 'EDIT_A_USER_FAILURE',
});

export default actionTypes;
